name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies and build React app
        run: |
          cd react-app  # If your React app is inside a folder called react-app
          npm install   # Install dependencies for the React app
          npm run build # Build the React app

      - name: Build CDK
        run: |
          npm install      # Install dependencies for the CDK
          npm run build     # Build the CDK project

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }} # AWS region from GitHub secrets

      - name: Deploy CDK Stack
        run: |
          npm install -g aws-cdk  # Install CDK globally
          cdk bootstrap            # Bootstraps the environment (if not already)
          cdk deploy --require-approval never  # Deploy the CDK stack without approval prompts
